AWSTemplateFormatVersion: 2010-09-09
Description: Provision EC2 Instance for testing POC 

###############################################################################################################################
# GLOBAL PARAMETER SECTION FOR ENV TYPE, VPC, PRIVATE SUBNETS, PROJECT, COST CENTER

###############################################################################################################################
Parameters:

  EnvType:
    Description: 'Environment type (eg, dev, test, prod)'
    Type: String
    AllowedValues:
      - evaluation
      - development
      - ftest
      - staging
      - ptest
      - production
    Default: evaluation
  AppName:
    Type: String
    Default: test 
  PrivateSubnetId01:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /serverless/global/misc/PrivateSubnetId01
  PrivateSubnetId02:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /serverless/global/misc/PrivateSubnetId02
  PrivateSubnetId03:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /serverless/global/misc/PrivateSubnetId03
  Project:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Project Code for AWS Resources
    Default: /serverless/global/misc/projectcode
  CostCenter:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Cost Center Details for AWS Resources
    Default: /serverless/global/misc/costcenter
  VpcId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: 'VPC Details'
    Default: /serverless/global/misc/vpcid
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the node instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: test # FOR EVALUATION 
    
  ImageId:
    Description: The AMI to create EC2 instances
    Type: String
    Default: 'ami-047a51fa27710816e'
Resources:
#################################################################################################################################

## LAUNCH TEMPLATE FOR EC2 INSTANCE

#################################################################################################################################
  
  TESTEC2LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: TEST 
      LaunchTemplateData:
        InstanceType: t3.nano 
        DisableApiTermination: 'true'
        KeyName: !Ref KeyName
        ImageId: !Ref ImageId 
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 10 
              VolumeType: gp2
              Encrypted: true
        SecurityGroupIds:
          - !Ref TESTSecurityGroupID
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: CostCenter
                Value: !Ref CostCenter
              - Key: Project
                Value: !Ref Project 
              - Key: Pod
                Value: TEST 
              - Key: Technology
                Value: TEST
        
  CAPESecurityGroupID:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Test POC' 
      GroupName: !Sub "${EnvType}-${AppName}-SG" 
      Tags:
        - Key: Name
          Value: TEST-POC 
        - Key: Project
          Value: !Ref Project 
        - Key: CostCenter
          Value: !Ref CostCenter 
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22 
          ToPort: 22 
          CidrIp: 0.0.0.0/0

  CAPEEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref 'TESTEC2InstanceRole']
  TESTEC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: EC2policy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - "ec2:*"
            Resource: '*'
#################################################################################################################################
### EC2 INSTANCE 
#################################################################################################################################
  TESTInstance:
    DependsOn: TESTEC2LaunchTemplate 
    Type: AWS::EC2::Instance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Snapshot
    Properties:
      Tags:
        - Key: Project
          Value: !Ref Project 
        - Key: CostCenter
          Value: !Ref CostCenter 
        - Key: Name
          Value: 'eval-test-ec2'

      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 10 
            VolumeType: gp2
            Encrypted: true
      IamInstanceProfile: !Ref TESTEC2InstanceProfile
      LaunchTemplate:
        LaunchTemplateName: TEST 
        Version: 1 
      InstanceInitiatedShutdownBehavior: stop
      SubnetId: !Ref PrivateSubnetId01 
      SecurityGroupIds:
         - !Ref TESTSecurityGroupID
############################################################################################################################
#  EC2  INSTANCES IP ADDRESS 
###########################################################################################################################
Outputs:
  CAPEInstance:
    Description: TEST EC2 Instance 
    Value:  !GetAtt TESTInstance.PrivateIp